### ISSUE TITLE
Uncaught TypeError: numArr is not a function

### ISSUE THREAD

**Issue by skanel** [moesaid/cleopatra#14]
**Describe the bug**
just clone the new repos and make it up running, but i got the following error: 

```
Uncaught TypeError: numArr is not a function
    at scripts.js:65
```

**Comment by moesaid** [comment]
make sure all the files are loaded/imported correctly.

**Comment by skanel** [comment]
it imported, sometimes it works , some time not.

I have run `npm run dev`,  I think the code has some issue of loading data for charts,
