### ISSUE TITLE
Where are UI elements?

### ISSUE THREAD

**Issue by potikorn** [moesaid/cleopatra#15]
![image](https://user-images.githubusercontent.com/18239662/128480496-6d16315d-a20a-4dc2-8263-11dbd473adc6.png)

I need to know where are the other UI element from content menu to below? 
Are you still development or something?

**Comment by moesaid** [comment]
I have that in mind, don't have the time for it yet but when I do I will notify you, you can also contribute, all pull requests are welcomed :)
