### ISSUE TITLE
TypeError: argument fn must be a function 

### ISSUE THREAD

**Issue by yuceltoluyag** [moesaid/cleopatra#4]
TypeError: argument fn must be a function 

 - windows 10

npm -v  => 6.9.0    
node -v  => v12.5.0 

npm run dev

`TypeError: argument fn must be a function                                                                                   at Function.wrapfunction [as function] (C:\Users\yucel\Desktop\cleopatra\node_modules\depd\index.js:399:11)             at populateConstructorExports (C:\Users\yucel\Desktop\cleopatra\node_modules\send\node_modules\http-errors\index.js:247:45)                                                                                                                     at Object.<anonymous> (C:\Users\yucel\Desktop\cleopatra\node_modules\send\node_modules\http-errors\index.js:29:1)       at Module._compile (internal/modules/cjs/loader.js:776:30)                                                              at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)                                                at Module.load (internal/modules/cjs/loader.js:643:32)                                                                  at Function.Module._load (internal/modules/cjs/loader.js:556:12)                                                        at Module.require (internal/modules/cjs/loader.js:683:19)                                                               at require (internal/modules/cjs/helpers.js:16:16)                                                                      at Object.<anonymous> (C:\Users\yucel\Desktop\cleopatra\node_modules\send\index.js:15:19)  `

**Comment by moesaid** [comment]
This problem occurs in Turkish workstations with newer versions of node.js.

You should change the system language or downgrade your node.js version.
